# -*- coding: utf-8 -*-
"""鱼种名单（按钓点分组）。由内容生成脚本产出，供 main.py 合并进 FISH_POOL。"""

LOCATION_ROSTERS: dict[str, list[dict]] = {
    "novice": [
        {"id": "novice_roach", "name": "白条", "rarity": "常见", "flavor": "细长的小鱼抢饵最积极"},
        {"id": "novice_crucian", "name": "鲫鱼", "rarity": "常见", "flavor": "池塘里最老实的小家伙"},
        {"id": "novice_loach", "name": "泥鳅", "rarity": "常见", "flavor": "滑得抓不住的黄褐色小条"},
        {"id": "novice_stone_moroko", "name": "麦穗鱼", "rarity": "常见", "flavor": "身侧一道黑线爱啄钩"},
        {"id": "novice_shrimp", "name": "小河虾", "rarity": "常见", "flavor": "透明得能看见肚里的沙"},
        {"id": "novice_snail", "name": "田螺", "rarity": "常见", "flavor": "壳口一圈青苔还带着泥"},
        {"id": "novice_bitterling", "name": "鳑鲏", "rarity": "常见", "flavor": "阳光下闪出彩虹般的鳞"},
        {"id": "novice_yellow_catfish", "name": "黄颡鱼", "rarity": "少见", "flavor": "背鳍竖起来扎手的黄胡子"},
        {"id": "novice_carp", "name": "鲤鱼", "rarity": "少见", "flavor": "尾巴一甩溅起半池水花"},
        {"id": "novice_mussel", "name": "河蚌", "rarity": "少见", "flavor": "壳缝里吐出一串小气泡"},
        {"id": "novice_turtle", "name": "巴西龟", "rarity": "少见", "flavor": "被人放生后长满了绿藻"},
        {"id": "novice_koi", "name": "锦鲤", "rarity": "稀有", "flavor": "红白花纹在浅水里游弋"},
    ],
    "bamboo": [
        {"id": "bamboo_chub", "name": "溪哥", "rarity": "常见", "flavor": "鳞片闪着溪水的亮光"},
        {"id": "bamboo_horsemouth", "name": "马口鱼", "rarity": "常见", "flavor": "嘴大贪吃见饵就往前冲"},
        {"id": "bamboo_river_snail", "name": "山坑螺", "rarity": "常见", "flavor": "吸在石头上扣都扣不动"},
        {"id": "bamboo_goby", "name": "虾虎鱼", "rarity": "常见", "flavor": "趴在卵石上一动不动"},
        {"id": "bamboo_barb", "name": "小鲃", "rarity": "常见", "flavor": "竹影下成群游来游去"},
        {"id": "bamboo_stream_crab", "name": "溪蟹", "rarity": "常见", "flavor": "举着小钳子横着走路"},
        {"id": "bamboo_labiobarbus", "name": "光唇鱼", "rarity": "少见", "flavor": "嘴唇厚实最爱啃青苔"},
        {"id": "bamboo_spiny_eel", "name": "刺鳅", "rarity": "少见", "flavor": "浑身细刺钻进石缝里"},
        {"id": "bamboo_corbicula", "name": "河蚬", "rarity": "少见", "flavor": "沙底上一排小小的纹路"},
        {"id": "bamboo_spiny_frog", "name": "棘胸蛙", "rarity": "少见", "flavor": "蹲在湿石上鼓着腮帮"},
        {"id": "bamboo_giant_salamander", "name": "娃娃鱼", "rarity": "稀有", "flavor": "溪水深处传来婴儿哭声"},
        {"id": "bamboo_peach_jellyfish", "name": "桃花水母", "rarity": "稀有", "flavor": "水中漂浮的淡粉色小伞"},
    ],
    "canal": [
        {"id": "canal_tilapia", "name": "罗非鱼", "rarity": "常见", "flavor": "污水里也活得膘肥体壮"},
        {"id": "canal_crayfish", "name": "小龙虾", "rarity": "常见", "flavor": "举着红钳从石缝里爬出"},
        {"id": "canal_old_boot", "name": "破靴子", "rarity": "常见", "flavor": "靴筒里还藏着两只小虾"},
        {"id": "canal_soda_can", "name": "易拉罐", "rarity": "常见", "flavor": "罐口卡着一只小螃蟹"},
        {"id": "canal_mosquitofish", "name": "食蚊鱼", "rarity": "常见", "flavor": "水面上一群指头长的小鱼"},
        {"id": "canal_mud_carp", "name": "鲮鱼", "rarity": "常见", "flavor": "贴着河底慢慢啃食青泥"},
        {"id": "canal_walking_catfish", "name": "塘鲺", "rarity": "少见", "flavor": "能在湿泥里扭着爬行"},
        {"id": "canal_mitten_crab", "name": "中华绒螯蟹", "rarity": "少见", "flavor": "毛茸茸的钳子夹住鱼线"},
        {"id": "canal_ricefield_eel", "name": "黄鳝", "rarity": "少见", "flavor": "从石阶缝里滑出半条身子"},
        {"id": "canal_silver_carp", "name": "鲢鱼", "rarity": "少见", "flavor": "受惊时跃出水面半米高"},
        {"id": "canal_alligator_snapper", "name": "鳄龟", "rarity": "稀有", "flavor": "咬合力惊人的放生怪物"},
        {"id": "canal_chinese_sucker", "name": "胭脂鱼", "rarity": "稀有", "flavor": "背鳍如帆通体泛着红光"},
    ],
    "lake": [
        {"id": "lake_bream", "name": "鳊鱼", "rarity": "常见", "flavor": "侧扁的身子像一片银叶"},
        {"id": "lake_icefish", "name": "银鱼", "rarity": "常见", "flavor": "几乎透明的细软小鱼"},
        {"id": "lake_shrimp", "name": "湖虾", "rarity": "常见", "flavor": "长须在水草间轻轻摆动"},
        {"id": "lake_grass_carp", "name": "草鱼", "rarity": "常见", "flavor": "拖着水草在浅湾里转悠"},
        {"id": "lake_whitefish", "name": "翘嘴白鱼", "rarity": "常见", "flavor": "追着小鱼把水面炸开花"},
        {"id": "lake_carp", "name": "鲤鱼", "rarity": "少见", "flavor": "金鳞一闪就钻进深水"},
        {"id": "lake_bighead_carp", "name": "鳙鱼", "rarity": "少见", "flavor": "大头慢慢吞下一口浮游"},
        {"id": "lake_catfish", "name": "鲶鱼", "rarity": "少见", "flavor": "两根长须在浑水里探路"},
        {"id": "lake_mussel", "name": "河蚌", "rarity": "少见", "flavor": "在泥底拖出一道浅沟"},
        {"id": "lake_black_carp", "name": "青鱼", "rarity": "稀有", "flavor": "力大得能把竿拉成弓"},
        {"id": "lake_mandarin_fish", "name": "鳜鱼", "rarity": "稀有", "flavor": "斑纹藏在石缝里等猎物"},
        {"id": "lake_giant_softshell", "name": "百年老鳖", "rarity": "稀有", "flavor": "背上刻满岁月的旧纹"},
    ],
    "reed": [
        {"id": "reed_frog", "name": "青蛙", "rarity": "常见", "flavor": "扑通一声跳进芦苇丛"},
        {"id": "reed_water_snake", "name": "水蛇", "rarity": "常见", "flavor": "贴着水面划出长长波纹"},
        {"id": "reed_reed_shrimp", "name": "芦苇虾", "rarity": "常见", "flavor": "攀在苇秆上随波摇晃"},
        {"id": "reed_river_snail", "name": "螺蛳", "rarity": "常见", "flavor": "壳上粘着几缕新鲜水草"},
        {"id": "reed_stone_moroko", "name": "麦穗鱼", "rarity": "常见", "flavor": "在苇影里成群打转"},
        {"id": "reed_yellow_catfish", "name": "黄颡鱼", "rarity": "少见", "flavor": "扎手的黄胡子在泥里拱"},
        {"id": "reed_river_crab", "name": "河蟹", "rarity": "少见", "flavor": "八条腿横着穿过浅滩"},
        {"id": "reed_leech", "name": "蚂蟥", "rarity": "少见", "flavor": "吸在腿上怎么拽都不松"},
        {"id": "reed_freshwater_prawn", "name": "青虾", "rarity": "少见", "flavor": "弹尾一缩窜出半米远"},
        {"id": "reed_snakehead", "name": "黑鱼", "rarity": "稀有", "flavor": "黑背破水像一枚鱼雷"},
        {"id": "reed_softshell_turtle", "name": "甲鱼", "rarity": "稀有", "flavor": "伸长脖子一口咬住饵"},
        {"id": "reed_pearl_mussel", "name": "珍珠蚌", "rarity": "稀有", "flavor": "壳里含着颗温润的珠子"},
    ],
    "sea": [
        {"id": "sea_hairtail", "name": "带鱼", "rarity": "常见", "flavor": "银亮长身像一把快刀"},
        {"id": "sea_yellow_croaker", "name": "黄鱼", "rarity": "常见", "flavor": "出水时咕咕叫个不停"},
        {"id": "sea_swimming_crab", "name": "梭子蟹", "rarity": "常见", "flavor": "两把尖钳护着满壳蟹黄"},
        {"id": "sea_white_shrimp", "name": "白虾", "rarity": "常见", "flavor": "一网拉上来活蹦乱跳"},
        {"id": "sea_pomfret", "name": "鲳鱼", "rarity": "少见", "flavor": "扁得像面镜子闪着光"},
        {"id": "sea_squid", "name": "鱿鱼", "rarity": "少见", "flavor": "喷出一团墨汁就逃走"},
        {"id": "sea_spanish_mackerel", "name": "鲅鱼", "rarity": "少见", "flavor": "银蓝背上满是花纹"},
        {"id": "sea_jellyfish", "name": "海蜇", "rarity": "少见", "flavor": "半透明地一伸又一缩"},
        {"id": "sea_red_seabream", "name": "真鲷", "rarity": "稀有", "flavor": "通体粉红像海里的樱花"},
        {"id": "sea_lobster", "name": "大龙虾", "rarity": "稀有", "flavor": "长须一弹溅起一片水花"},
        {"id": "sea_tuna", "name": "金枪鱼", "rarity": "稀有", "flavor": "肌肉绷紧拖着鱼线狂奔"},
        {"id": "sea_oarfish", "name": "皇带鱼", "rarity": "传说", "flavor": "银带般的身子长得望不到头"},
    ],
    "dock": [
        {"id": "dock_seabass", "name": "鲈鱼", "rarity": "常见", "flavor": "在桥墩阴影里伏击小鱼"},
        {"id": "dock_old_tire", "name": "旧轮胎", "rarity": "常见", "flavor": "胎壁里住着一窝小蟹"},
        {"id": "dock_shore_crab", "name": "小螃蟹", "rarity": "常见", "flavor": "举着钳子卡住鱼钩不放"},
        {"id": "dock_sardine", "name": "沙丁鱼", "rarity": "常见", "flavor": "成群绕着木桩打转"},
        {"id": "dock_eel", "name": "鳗鱼", "rarity": "少见", "flavor": "缠住鱼线怎么都解不开"},
        {"id": "dock_octopus", "name": "章鱼", "rarity": "少见", "flavor": "八条腕抱着鱼饵不撒手"},
        {"id": "dock_starfish", "name": "海星", "rarity": "少见", "flavor": "五只角慢慢翻过木桩"},
        {"id": "dock_barnacle", "name": "藤壶", "rarity": "少见", "flavor": "密密麻麻糊满整块船板"},
        {"id": "dock_black_seabream", "name": "黑鲷", "rarity": "稀有", "flavor": "黑色鳍边一收就钻底"},
        {"id": "dock_stonefish", "name": "石头鱼", "rarity": "稀有", "flavor": "装作石块等人踩上去"},
        {"id": "dock_seahorse", "name": "海马", "rarity": "稀有", "flavor": "蜷着尾巴挂在旧缆绳上"},
        {"id": "dock_megalodon", "name": "巨齿鲨", "rarity": "传说", "flavor": "旧码头外掀起三米巨浪"},
    ],
    "night": [
        {"id": "night_catfish", "name": "鲶鱼", "rarity": "常见", "flavor": "月光下贴着堤根巡游"},
        {"id": "night_loach", "name": "泥鳅", "rarity": "常见", "flavor": "夜里钻出泥底四处乱窜"},
        {"id": "night_river_shrimp", "name": "河虾", "rarity": "常见", "flavor": "月影里闪着透明的小点"},
        {"id": "night_topmouth", "name": "翘嘴白鱼", "rarity": "常见", "flavor": "炸水声传遍整个堤坝"},
        {"id": "night_lanternfish", "name": "灯笼鱼", "rarity": "少见", "flavor": "一排小灯在暗水里游过"},
        {"id": "night_opah", "name": "月鱼", "rarity": "少见", "flavor": "鳞片映着月色泛出红光"},
        {"id": "night_glow_jellyfish", "name": "夜光水母", "rarity": "少见", "flavor": "蓝光一闪一闪浮上来"},
        {"id": "night_giant_catfish", "name": "巨型鲶鱼", "rarity": "稀有", "flavor": "拖得鱼竿弯进水里"},
        {"id": "night_moonlit_eel", "name": "银月鳗", "rarity": "稀有", "flavor": "银色身子像一道月光"},
        {"id": "night_ghost_lanternfish", "name": "幽灵灯笼鱼", "rarity": "稀有", "flavor": "幽绿的光在深处熄灭"},
        {"id": "night_glow_shark", "name": "夜光鲨", "rarity": "稀有", "flavor": "背鳍划开墨色的水面"},
        {"id": "night_white_dragon_fish", "name": "白龙鱼", "rarity": "传说", "flavor": "月光里跃出一条白影"},
    ],
    "mangrove": [
        {"id": "mangrove_mudskipper", "name": "弹涂鱼", "rarity": "常见", "flavor": "用胸鳍在泥滩上蹦跳"},
        {"id": "mangrove_fiddler_crab", "name": "招潮蟹", "rarity": "常见", "flavor": "举着一只大钳来回招手"},
        {"id": "mangrove_oyster", "name": "牡蛎", "rarity": "常见", "flavor": "牢牢粘在红树根上"},
        {"id": "mangrove_baby_shark", "name": "幼鲨", "rarity": "少见", "flavor": "在浅湾里练习捕猎"},
        {"id": "mangrove_mud_snail", "name": "泥螺", "rarity": "少见", "flavor": "拖着黏液在泥面爬行"},
        {"id": "mangrove_prawn", "name": "基围虾", "rarity": "少见", "flavor": "在树根之间弹跳逃窜"},
        {"id": "mangrove_mud_crab", "name": "青蟹", "rarity": "少见", "flavor": "青壳大钳夹得人发麻"},
        {"id": "mangrove_horseshoe_crab", "name": "中华鲎", "rarity": "稀有", "flavor": "蓝血甲壳像一顶小钢盔"},
        {"id": "mangrove_saltwater_crocodile", "name": "湾鳄", "rarity": "稀有", "flavor": "浮木般的背脊缓缓移动"},
        {"id": "mangrove_giant_python", "name": "巨蟒", "rarity": "稀有", "flavor": "从树根间垂下半个身子"},
        {"id": "mangrove_dugong", "name": "儒艮", "rarity": "稀有", "flavor": "笨拙地抱着水草啃食"},
        {"id": "mangrove_flood_dragon", "name": "蛟龙", "rarity": "传说", "flavor": "潮水翻涌时探出长角"},
    ],
    "swamp": [
        {"id": "swamp_marsh_shrimp", "name": "沼虾", "rarity": "常见", "flavor": "雾气里挥着细长的钳"},
        {"id": "swamp_water_snail", "name": "水蜗牛", "rarity": "常见", "flavor": "背着壳在浮叶上爬"},
        {"id": "swamp_newt", "name": "蝾螈", "rarity": "常见", "flavor": "橙腹的小东西扭着尾巴"},
        {"id": "swamp_ricefield_eel", "name": "黄鳝", "rarity": "少见", "flavor": "从腐叶底下滑出一截"},
        {"id": "swamp_marsh_turtle", "name": "沼泽龟", "rarity": "少见", "flavor": "壳上长满绿毛像块石头"},
        {"id": "swamp_water_snake", "name": "水蛇", "rarity": "少见", "flavor": "雾气中划开一道水痕"},
        {"id": "swamp_toad", "name": "蟾蜍", "rarity": "少见", "flavor": "鼓着喉咙发出低哑叫声"},
        {"id": "swamp_alligator_gar", "name": "鳄雀鳝", "rarity": "稀有", "flavor": "满口尖牙咬得鱼线发白"},
        {"id": "swamp_loach_king", "name": "泥鳅王", "rarity": "稀有", "flavor": "手臂粗的泥鳅搅翻泥浆"},
        {"id": "swamp_giant_leech", "name": "巨型水蛭", "rarity": "稀有", "flavor": "黑亮的身子缠上小腿"},
        {"id": "swamp_nine_eyed_fish", "name": "九目怪鱼", "rarity": "传说", "flavor": "九只眼睛同时转向你"},
        {"id": "swamp_ghost_catfish", "name": "幽冥巨鲶", "rarity": "传说", "flavor": "雾里传来低沉的吞咽声"},
    ],
    "cave": [
        {"id": "cave_blindfish", "name": "盲鱼", "rarity": "常见", "flavor": "没有眼睛也能找到饵"},
        {"id": "cave_cave_shrimp", "name": "洞穴虾", "rarity": "常见", "flavor": "通体雪白在暗水里漂"},
        {"id": "cave_albino_tadpole", "name": "白化蝌蚪", "rarity": "常见", "flavor": "苍白的小尾巴摆动不停"},
        {"id": "cave_cave_snail", "name": "洞穴螺", "rarity": "少见", "flavor": "壳薄得能看见里面的肉"},
        {"id": "cave_albino_catfish", "name": "白化鲶", "rarity": "少见", "flavor": "白色长须在黑暗里摸索"},
        {"id": "cave_blind_eel", "name": "盲眼鳗", "rarity": "少见", "flavor": "顺着暗流无声地滑过"},
        {"id": "cave_olm", "name": "洞螈", "rarity": "稀有", "flavor": "粉白的小龙趴在石上"},
        {"id": "cave_albino_giant_salamander", "name": "白化巨鲵", "rarity": "稀有", "flavor": "巨大白影贴着河底移动"},
        {"id": "cave_stone_spirit_fish", "name": "石灵鱼", "rarity": "稀有", "flavor": "鳞片像会呼吸的钟乳石"},
        {"id": "cave_glow_jellyfish", "name": "幽光水母", "rarity": "稀有", "flavor": "幽蓝冷光点亮整条暗河"},
        {"id": "cave_blind_white_dragon", "name": "盲眼白龙", "rarity": "传说", "flavor": "无眼的巨首擦过岩壁"},
        {"id": "cave_earthcore_sturgeon", "name": "地心鲟", "rarity": "传说", "flavor": "骨板厚重如远古铠甲"},
    ],
    "ruins": [
        {"id": "ruins_grouper", "name": "石斑鱼", "rarity": "常见", "flavor": "斑驳的身影守在船舷边"},
        {"id": "ruins_clownfish", "name": "小丑鱼", "rarity": "常见", "flavor": "在海葵触手间钻来钻去"},
        {"id": "ruins_sea_turtle", "name": "海龟", "rarity": "少见", "flavor": "慢悠悠绕过断裂的桅杆"},
        {"id": "ruins_lionfish", "name": "狮子鱼", "rarity": "少见", "flavor": "张开满身毒鳍缓缓逼近"},
        {"id": "ruins_sea_urchin", "name": "海胆", "rarity": "少见", "flavor": "黑刺扎进手套里发麻"},
        {"id": "ruins_wreck_crab", "name": "沉船蟹", "rarity": "少见", "flavor": "从锈蚀的舱门里爬出"},
        {"id": "ruins_treasure_chest_fish", "name": "宝箱鱼", "rarity": "稀有", "flavor": "鳞片像铜锁闪着暗光"},
        {"id": "ruins_giant_grouper", "name": "巨型石斑", "rarity": "稀有", "flavor": "一张嘴能吞下整条鱼"},
        {"id": "ruins_rusty_swordfish", "name": "锈剑鱼", "rarity": "稀有", "flavor": "长吻上缠着旧船的铁锈"},
        {"id": "ruins_pearl_king_clam", "name": "珍珠王贝", "rarity": "稀有", "flavor": "壳里滚出拳头大的珍珠"},
        {"id": "ruins_ghost_shark", "name": "幽灵鲨", "rarity": "传说", "flavor": "半透明的影子穿过船骸"},
        {"id": "ruins_sunken_leviathan", "name": "沉船巨鲲", "rarity": "传说", "flavor": "船体震动它正从下方经过"},
    ],
    "abyss": [
        {"id": "abyss_deep_sea_shrimp", "name": "深海虾", "rarity": "常见", "flavor": "苍白细腿在泥底摸索"},
        {"id": "abyss_deep_sea_crab", "name": "深海蟹", "rarity": "常见", "flavor": "盲眼长腿抱着一块腐肉"},
        {"id": "abyss_deep_sea_eel", "name": "深海鳗", "rarity": "少见", "flavor": "张开大口等着一切落下"},
        {"id": "abyss_sail_jellyfish", "name": "帆水母", "rarity": "少见", "flavor": "像一片蓝色小帆漂过去"},
        {"id": "abyss_deep_octopus", "name": "深海章鱼", "rarity": "少见", "flavor": "吸盘在舷边留下圆痕"},
        {"id": "abyss_anglerfish", "name": "鮟鱇鱼", "rarity": "稀有", "flavor": "头顶小灯照出满口尖牙"},
        {"id": "abyss_giant_squid", "name": "巨型乌贼", "rarity": "稀有", "flavor": "触腕上密布着倒钩"},
        {"id": "abyss_vampire_squid", "name": "吸血乌贼", "rarity": "稀有", "flavor": "披着黑红斗篷缓缓飘过"},
        {"id": "abyss_dragonfish", "name": "深海龙鱼", "rarity": "稀有", "flavor": "獠牙长到合不上嘴"},
        {"id": "abyss_colossal_squid", "name": "大王酸浆鱿", "rarity": "传说", "flavor": "眼球比人头还大的家伙"},
        {"id": "abyss_megamouth_shark", "name": "巨口鲨", "rarity": "传说", "flavor": "巨口张开像一张大网"},
        {"id": "abyss_leviathan", "name": "利维坦", "rarity": "神话", "flavor": "海沟深处传来远古咆哮"},
    ],
    "trench": [
        {"id": "trench_amphipod", "name": "端足虫", "rarity": "常见", "flavor": "指甲盖大的白虫翻着泥"},
        {"id": "trench_ghost_shrimp", "name": "幽灵虾", "rarity": "常见", "flavor": "半透明的影子掠过探照灯"},
        {"id": "trench_snailfish", "name": "狮子鱼", "rarity": "少见", "flavor": "胶质身体在万米下漂浮"},
        {"id": "trench_sea_pig", "name": "海猪", "rarity": "少见", "flavor": "粉胖的身子用细腿走路"},
        {"id": "trench_glass_sponge", "name": "玻璃海绵", "rarity": "少见", "flavor": "骨架像一件透明工艺品"},
        {"id": "trench_sixgill_shark", "name": "六鳃鲨", "rarity": "稀有", "flavor": "远古的轮廓从黑暗中浮出"},
        {"id": "trench_ghost_octopus", "name": "幽灵蛸", "rarity": "稀有", "flavor": "深红斗篷在无光处张开"},
        {"id": "trench_gulper_eel", "name": "巨口鳗", "rarity": "稀有", "flavor": "能把嘴张得比身体还大"},
        {"id": "trench_spider_crab", "name": "巨蛛蟹", "rarity": "传说", "flavor": "长腿跨过整个探测窗口"},
        {"id": "trench_dark_sea_serpent", "name": "无光海蛇", "rarity": "传说", "flavor": "黑暗中只有鳞片在反光"},
        {"id": "trench_thousand_eye_fish", "name": "万眼鱼", "rarity": "传说", "flavor": "每只眼睛都盯着不同方向"},
        {"id": "trench_guixu", "name": "归墟", "rarity": "神话", "flavor": "万水归处连光都无法逃出"},
    ],
    "glacier": [
        {"id": "glacier_cod", "name": "鳕鱼", "rarity": "常见", "flavor": "冰凉水里肉质格外紧实"},
        {"id": "glacier_ice_shrimp", "name": "冰虾", "rarity": "常见", "flavor": "在冰洞下闪着细碎的光"},
        {"id": "glacier_arctic_char", "name": "冰鲑", "rarity": "少见", "flavor": "红腹在冰下格外醒目"},
        {"id": "glacier_ice_snail", "name": "冰螺", "rarity": "少见", "flavor": "壳上结着一层薄薄的冰"},
        {"id": "glacier_snow_crab", "name": "雪蟹", "rarity": "少见", "flavor": "白壳长腿在冰底爬行"},
        {"id": "glacier_arctic_sturgeon", "name": "极地鳇", "rarity": "稀有", "flavor": "破冰而出掀起大片水花"},
        {"id": "glacier_ice_jellyfish", "name": "冰晶水母", "rarity": "稀有", "flavor": "冻成晶体的伞盖仍在动"},
        {"id": "glacier_ice_turtle", "name": "千年冰龟", "rarity": "稀有", "flavor": "龟壳冻成了半透明的冰"},
        {"id": "glacier_arctic_seal", "name": "北极海豹", "rarity": "传说", "flavor": "圆滚滚的家伙抢走鱼饵"},
        {"id": "glacier_frozen_whale", "name": "冰封巨鲸", "rarity": "传说", "flavor": "冰层下传来悠长的鲸歌"},
        {"id": "glacier_cod_king", "name": "极光鳕王", "rarity": "传说", "flavor": "鳞片映出整片绿色天光"},
        {"id": "glacier_glacier_heart", "name": "冰川之心", "rarity": "神话", "flavor": "冰下传来缓慢的搏动声"},
    ],
    "aurora": [
        {"id": "aurora_aurora_shrimp", "name": "极光虾", "rarity": "常见", "flavor": "壳上流转着淡淡的绿光"},
        {"id": "aurora_aurora_cod", "name": "极光鳕", "rarity": "少见", "flavor": "在光幕下游成一条长线"},
        {"id": "aurora_stardust_jellyfish", "name": "星尘水母", "rarity": "少见", "flavor": "触须上落满细小的光点"},
        {"id": "aurora_crystal_crab", "name": "冰晶蟹", "rarity": "少见", "flavor": "钳子上凝着蓝白的霜花"},
        {"id": "aurora_aurora_salmon", "name": "极光鲑", "rarity": "稀有", "flavor": "逆着光瀑向上游动"},
        {"id": "aurora_starlight_eel", "name": "星辉鳗", "rarity": "稀有", "flavor": "身上流转着银河般的纹"},
        {"id": "aurora_light_pillar_fish", "name": "光柱鱼", "rarity": "稀有", "flavor": "把极光折成一根根光柱"},
        {"id": "aurora_sky_whale", "name": "天穹巨鲸", "rarity": "传说", "flavor": "影子投在整片极光之上"},
        {"id": "aurora_aurora_dragonfish", "name": "极光龙鱼", "rarity": "传说", "flavor": "鳞片把整片天幕照得发亮"},
        {"id": "aurora_star_orbit_jellyfish", "name": "星轨水母", "rarity": "传说", "flavor": "伞盖旋转如一片星轨"},
        {"id": "aurora_eternal_night_sturgeon", "name": "永夜冰鲟", "rarity": "传说", "flavor": "骨板下压着整片永夜"},
        {"id": "aurora_aurora_primordial_dragon", "name": "极光古龙", "rarity": "神话", "flavor": "光幕裂开它缓缓垂下头"},
    ],
}
